blank_issues_enabled: false
contact_links:
  - name: API Repository
    url: https://github.com/Pirate-Weather/pirateweather/
    about: Report issues with and request features to the API here. If the integration is reporting an error due to an Internal Server Error then the issue should be reported here.
